import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'pixel-quest',
  slug: 'pixel-quest',
  title: 'Pixel Quest',
  description: 'Aventure-se em um mundo pixelado cheio de desafios.',
  shortDescription: 'Aventura em mundo pixelado.',
  thumbnail: 'https://picsum.photos/id/38/400/300',
  cover: 'https://picsum.photos/seed/pixel-quest-cover/800/600',
  categoryId: 'arcade',
  category: 'Arcade',
  difficulty: 'Medium',
  players: '1',
  averagePlayTime: '15 min',
  averagePlayTimeMinutes: 15,
  tags: ["Arcade", "Aventura"],
  featured: false,
  popular: false,
  isNew: true,
  status: 'published',
  version: '1.0.0',
  rating: 4.4,
  gradient: 'from-lime-500 to-green-600',
  releaseDate: '2025-01-10',
}
