export { HeroSection } from './HeroSection'
export { FeaturedGames } from './FeaturedGames'
export { CategoriesSection } from './CategoriesSection'
export { ContinueExploring } from './ContinueExploring'
export { StatsSection } from './StatsSection'
export { HowItWorks } from './HowItWorks'
export { BenefitsSection } from './BenefitsSection'
export { FinalCTA } from './FinalCTA'
