import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'space-invaders',
  slug: 'space-invaders',
  title: 'Space Invaders',
  description: 'Defenda a Terra dos invasores alienígenas.',
  shortDescription: 'Defenda a Terra dos alienígenas.',
  thumbnail: 'https://picsum.photos/id/42/400/300',
  cover: 'https://picsum.photos/seed/space-invaders-cover/800/600',
  categoryId: 'arcade',
  category: 'Arcade',
  difficulty: 'Medium',
  players: '1',
  averagePlayTime: '10 min',
  averagePlayTimeMinutes: 10,
  tags: ["Arcade", "Clássico"],
  featured: true,
  popular: true,
  isNew: false,
  status: 'published',
  version: '1.0.0',
  rating: 4.6,
  gradient: 'from-cyan-500 to-blue-600',
  releaseDate: '2024-04-12',
}
