import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'sudoku',
  slug: 'sudoku',
  title: 'Sudoku',
  description: 'Preencha a grade com números sem repetir.',
  shortDescription: 'Preencha a grade de números.',
  thumbnail: 'https://picsum.photos/id/164/400/300',
  cover: 'https://picsum.photos/seed/sudoku-cover/800/600',
  categoryId: 'puzzle',
  category: 'Puzzle',
  difficulty: 'Medium',
  players: '1',
  averagePlayTime: '20 min',
  averagePlayTimeMinutes: 20,
  tags: ["Puzzle", "Offline"],
  featured: false,
  popular: false,
  isNew: false,
  status: 'published',
  version: '1.0.0',
  rating: 4.6,
  gradient: 'from-indigo-500 to-violet-600',
  releaseDate: '2024-09-18',
}
