import type { Game } from '@/types/game'

export const GAMES: Game[] = [
  {
    id: 'snake',
    title: 'Snake',
    slug: 'snake',
    description: 'O clássico jogo da cobrinha. Coma, cresça e não bata na parede.',
    categoryId: 'classicos',
    difficulty: 'Easy',
    playTime: '5 min',
    gradient: 'from-emerald-500 to-teal-600',
    featured: true,
  },
  {
    id: 'pong',
    title: 'Pong',
    slug: 'pong',
    description: 'O lendário jogo de tênis de mesa que iniciou tudo.',
    categoryId: 'classicos',
    difficulty: 'Medium',
    playTime: '5 min',
    gradient: 'from-violet-500 to-purple-600',
    featured: true,
  },
  {
    id: 'memory',
    title: 'Jogo da Memória',
    slug: 'memory',
    description: 'Encontre todos os pares e teste sua memória.',
    categoryId: 'memoria',
    difficulty: 'Easy',
    playTime: '10 min',
    gradient: 'from-pink-500 to-rose-600',
    featured: true,
  },
  {
    id: 'tictactoe',
    title: 'Jogo da Velha',
    slug: 'tictactoe',
    description: 'O clássico jogo de estratégia para dois jogadores.',
    categoryId: 'estrategia',
    difficulty: 'Easy',
    playTime: '3 min',
    gradient: 'from-amber-500 to-orange-600',
    featured: true,
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    slug: 'space-invaders',
    description: 'Defenda a Terra dos invasores alienígenas.',
    categoryId: 'arcade',
    difficulty: 'Medium',
    playTime: '10 min',
    gradient: 'from-cyan-500 to-blue-600',
    featured: true,
  },
  {
    id: 'pacman',
    title: 'Pac-Man',
    slug: 'pacman',
    description: 'Coma todos os pontos e fuja dos fantasmas.',
    categoryId: 'classicos',
    difficulty: 'Medium',
    playTime: '15 min',
    gradient: 'from-yellow-500 to-amber-600',
    featured: true,
  },
  {
    id: 'breakout',
    title: 'Breakout',
    slug: 'breakout',
    description: 'Destrua todos os blocos com a bola.',
    categoryId: 'arcade',
    difficulty: 'Medium',
    playTime: '10 min',
    gradient: 'from-red-500 to-rose-600',
    featured: true,
  },
  {
    id: 'tetris',
    title: 'Tetris',
    slug: 'tetris',
    description: 'O lendário jogo de blocos que desafia seus reflexos.',
    categoryId: 'reflexo',
    difficulty: 'Hard',
    playTime: '20 min',
    gradient: 'from-sky-500 to-indigo-600',
    featured: true,
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    slug: 'flappy-bird',
    description: 'Toque para voar e desvie dos canos.',
    categoryId: 'reflexo',
    difficulty: 'Hard',
    playTime: '5 min',
    gradient: 'from-sky-400 to-blue-500',
    featured: false,
  },
  {
    id: 'dino-run',
    title: 'Dino Run',
    slug: 'dino-run',
    description: 'Corra sem parar e desvie dos obstáculos.',
    categoryId: 'arcade',
    difficulty: 'Medium',
    playTime: '10 min',
    gradient: 'from-stone-500 to-zinc-600',
    featured: false,
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    slug: 'sudoku',
    description: 'Preencha a grade com números sem repetir.',
    categoryId: 'puzzle',
    difficulty: 'Medium',
    playTime: '20 min',
    gradient: 'from-indigo-500 to-violet-600',
    featured: false,
  },
  {
    id: 'xadrez',
    title: 'Xadrez',
    slug: 'xadrez',
    description: 'O clássico jogo de estratégia milenar.',
    categoryId: 'estrategia',
    difficulty: 'Hard',
    playTime: '30 min',
    gradient: 'from-neutral-600 to-zinc-700',
    featured: false,
  },
]

export const FEATURED_GAMES = GAMES.filter((game) => game.featured)

export const GAMES_PER_PAGE = 8
