import type { Game } from '@/types/game'

export const GAMES: Game[] = [
  {
    id: 'snake',
    title: 'Snake',
    slug: 'snake',
    description: 'O clássico jogo da cobrinha. Coma, cresça e não bata na parede.',
    categoryId: 'classicos',
    difficulty: 'Easy',
    playTime: '5 min',
    playTimeMinutes: 5,
    gradient: 'from-emerald-500 to-teal-600',
    featured: true,
    rating: 4.5,
    players: '1',
    tags: ['Clássico', 'Arcade'],
    new: false,
    popular: true,
    releaseDate: '2024-01-15',
    urlPhoto: 'https://picsum.photos/id/1/800/600',
  },
  {
    id: 'pong',
    title: 'Pong',
    slug: 'pong',
    description: 'O lendário jogo de tênis de mesa que iniciou tudo.',
    categoryId: 'classicos',
    difficulty: 'Medium',
    playTime: '5 min',
    playTimeMinutes: 5,
    gradient: 'from-violet-500 to-purple-600',
    featured: true,
    rating: 4.3,
    players: '1-2',
    tags: ['Clássico', 'Esporte'],
    new: false,
    popular: true,
    releaseDate: '2024-02-10',
    urlPhoto: 'https://picsum.photos/id/96/800/600',
  },
  {
    id: 'memory',
    title: 'Jogo da Memória',
    slug: 'memory',
    description: 'Encontre todos os pares e teste sua memória.',
    categoryId: 'memoria',
    difficulty: 'Easy',
    playTime: '10 min',
    playTimeMinutes: 10,
    gradient: 'from-pink-500 to-rose-600',
    featured: true,
    rating: 4.7,
    players: '1',
    tags: ['Casual', 'Offline'],
    new: false,
    popular: true,
    releaseDate: '2024-03-05',
    urlPhoto: 'https://picsum.photos/id/20/800/600',
  },
  {
    id: 'tictactoe',
    title: 'Jogo da Velha',
    slug: 'tictactoe',
    description: 'O clássico jogo de estratégia para dois jogadores.',
    categoryId: 'estrategia',
    difficulty: 'Easy',
    playTime: '3 min',
    playTimeMinutes: 3,
    gradient: 'from-amber-500 to-orange-600',
    featured: true,
    rating: 4.1,
    players: '1-2',
    tags: ['Estratégia', 'Clássico'],
    new: false,
    popular: false,
    releaseDate: '2024-01-20',
    urlPhoto: 'https://picsum.photos/id/26/800/600',
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    slug: 'space-invaders',
    description: 'Defenda a Terra dos invasores alienígenas.',
    categoryId: 'arcade',
    difficulty: 'Medium',
    playTime: '10 min',
    playTimeMinutes: 10,
    gradient: 'from-cyan-500 to-blue-600',
    featured: true,
    rating: 4.6,
    players: '1',
    tags: ['Arcade', 'Clássico'],
    new: false,
    popular: true,
    releaseDate: '2024-04-12',
    urlPhoto: 'https://picsum.photos/id/42/800/600',
  },
  {
    id: 'pacman',
    title: 'Pac-Man',
    slug: 'pacman',
    description: 'Coma todos os pontos e fuja dos fantasmas.',
    categoryId: 'classicos',
    difficulty: 'Medium',
    playTime: '15 min',
    playTimeMinutes: 15,
    gradient: 'from-yellow-500 to-amber-600',
    featured: true,
    rating: 4.8,
    players: '1',
    tags: ['Clássico', 'Arcade'],
    new: false,
    popular: true,
    releaseDate: '2024-05-01',
    urlPhoto: 'https://picsum.photos/id/60/800/600',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    slug: 'breakout',
    description: 'Destrua todos os blocos com a bola.',
    categoryId: 'arcade',
    difficulty: 'Medium',
    playTime: '10 min',
    playTimeMinutes: 10,
    gradient: 'from-red-500 to-rose-600',
    featured: true,
    rating: 4.2,
    players: '1',
    tags: ['Arcade', 'Clássico'],
    new: false,
    popular: false,
    releaseDate: '2024-02-28',
    urlPhoto: 'https://picsum.photos/id/48/800/600',
  },
  {
    id: 'tetris',
    title: 'Tetris',
    slug: 'tetris',
    description: 'O lendário jogo de blocos que desafia seus reflexos.',
    categoryId: 'reflexo',
    difficulty: 'Hard',
    playTime: '20 min',
    playTimeMinutes: 20,
    gradient: 'from-sky-500 to-indigo-600',
    featured: true,
    rating: 4.9,
    players: '1',
    tags: ['Clássico', 'Puzzle'],
    new: false,
    popular: true,
    releaseDate: '2024-06-10',
    urlPhoto: 'https://picsum.photos/id/36/800/600',
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    slug: 'flappy-bird',
    description: 'Toque para voar e desvie dos canos.',
    categoryId: 'reflexo',
    difficulty: 'Hard',
    playTime: '5 min',
    playTimeMinutes: 5,
    gradient: 'from-sky-400 to-blue-500',
    featured: false,
    rating: 4.0,
    players: '1',
    tags: ['Arcade', 'Casual'],
    new: false,
    popular: true,
    releaseDate: '2024-07-22',
    urlPhoto: 'https://picsum.photos/id/217/800/600',
  },
  {
    id: 'dino-run',
    title: 'Dino Run',
    slug: 'dino-run',
    description: 'Corra sem parar e desvie dos obstáculos.',
    categoryId: 'arcade',
    difficulty: 'Medium',
    playTime: '10 min',
    playTimeMinutes: 10,
    gradient: 'from-stone-500 to-zinc-600',
    featured: false,
    rating: 4.3,
    players: '1',
    tags: ['Arcade', 'Offline'],
    new: false,
    popular: false,
    releaseDate: '2024-08-05',
    urlPhoto: 'https://picsum.photos/id/125/800/600',
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    slug: 'sudoku',
    description: 'Preencha a grade com números sem repetir.',
    categoryId: 'puzzle',
    difficulty: 'Medium',
    playTime: '20 min',
    playTimeMinutes: 20,
    gradient: 'from-indigo-500 to-violet-600',
    featured: false,
    rating: 4.6,
    players: '1',
    tags: ['Puzzle', 'Offline'],
    new: false,
    popular: false,
    releaseDate: '2024-09-18',
    urlPhoto: 'https://picsum.photos/id/164/800/600',
  },
  {
    id: 'xadrez',
    title: 'Xadrez',
    slug: 'xadrez',
    description: 'O clássico jogo de estratégia milenar.',
    categoryId: 'estrategia',
    difficulty: 'Hard',
    playTime: '30 min',
    playTimeMinutes: 30,
    gradient: 'from-neutral-600 to-zinc-700',
    featured: false,
    rating: 4.7,
    players: '1-2',
    tags: ['Estratégia', 'Clássico', 'Offline'],
    new: false,
    popular: false,
    releaseDate: '2024-10-01',
    urlPhoto: 'https://picsum.photos/id/262/800/600',
  },
  {
    id: 'pixel-quest',
    title: 'Pixel Quest',
    slug: 'pixel-quest',
    description: 'Aventure-se em um mundo pixelado cheio de desafios.',
    categoryId: 'arcade',
    difficulty: 'Medium',
    playTime: '15 min',
    playTimeMinutes: 15,
    gradient: 'from-lime-500 to-green-600',
    featured: false,
    rating: 4.4,
    players: '1',
    tags: ['Arcade', 'Aventura'],
    new: true,
    popular: false,
    releaseDate: '2025-01-10',
    urlPhoto: 'https://picsum.photos/id/38/800/600',
  },
  {
    id: 'color-match',
    title: 'Color Match',
    slug: 'color-match',
    description: 'Combine as cores antes que o tempo acabe.',
    categoryId: 'reflexo',
    difficulty: 'Easy',
    playTime: '5 min',
    playTimeMinutes: 5,
    gradient: 'from-fuchsia-500 to-purple-600',
    featured: false,
    rating: 3.9,
    players: '1',
    tags: ['Casual', 'Reflexo'],
    new: true,
    popular: false,
    releaseDate: '2025-02-14',
  },
  {
    id: 'campo-minado',
    title: 'Campo Minado',
    slug: 'campo-minado',
    description: 'Encontre todas as minas sem explodi-las.',
    categoryId: 'puzzle',
    difficulty: 'Medium',
    playTime: '15 min',
    playTimeMinutes: 15,
    gradient: 'from-slate-500 to-gray-600',
    featured: false,
    rating: 4.2,
    players: '1',
    tags: ['Puzzle', 'Clássico', 'Offline'],
    new: false,
    popular: false,
    releaseDate: '2024-04-20',
  },
  {
    id: 'forca',
    title: 'Jogo da Forca',
    slug: 'forca',
    description: 'Descubra a palavra secreta antes de ser enforcado.',
    categoryId: 'sorte',
    difficulty: 'Easy',
    playTime: '10 min',
    playTimeMinutes: 10,
    gradient: 'from-teal-500 to-emerald-600',
    featured: false,
    rating: 4.0,
    players: '1-2',
    tags: ['Casual', 'Palavras'],
    new: false,
    popular: false,
    releaseDate: '2024-05-15',
  },
]

export const FEATURED_GAMES = GAMES.filter((g) => g.featured)
export const GAMES_PER_PAGE = 8
