import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'pong',
  slug: 'pong',
  title: 'Pong',
  description: 'O lendário jogo de tênis de mesa que iniciou tudo.',
  shortDescription: 'O lendário jogo de tênis de mesa.',
  thumbnail: 'https://picsum.photos/id/96/400/300',
  cover: 'https://picsum.photos/seed/pong-cover/800/600',
  categoryId: 'classicos',
  category: 'Clássicos',
  difficulty: 'Medium',
  players: '1-2',
  averagePlayTime: '5 min',
  averagePlayTimeMinutes: 5,
  tags: ["Clássico", "Esporte"],
  featured: true,
  popular: true,
  isNew: false,
  status: 'published',
  version: '1.0.0',
  rating: 4.3,
  gradient: 'from-violet-500 to-purple-600',
  releaseDate: '2024-02-10',
}
