import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'breakout',
  slug: 'breakout',
  title: 'Breakout',
  description: 'Destrua todos os blocos com a bola.',
  shortDescription: 'Destrua blocos com a bola.',
  thumbnail: 'https://picsum.photos/id/48/400/300',
  cover: 'https://picsum.photos/seed/breakout-cover/800/600',
  categoryId: 'arcade',
  category: 'Arcade',
  difficulty: 'Medium',
  players: '1',
  averagePlayTime: '10 min',
  averagePlayTimeMinutes: 10,
  tags: ["Arcade", "Clássico"],
  featured: true,
  popular: false,
  isNew: false,
  status: 'published',
  version: '1.0.0',
  rating: 4.2,
  gradient: 'from-red-500 to-rose-600',
  releaseDate: '2024-02-28',
}
