import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'tictactoe',
  slug: 'tictactoe',
  title: 'Jogo da Velha',
  description: 'O clássico jogo de estratégia para dois jogadores.',
  shortDescription: 'Estratégia clássica para dois jogadores.',
  thumbnail: 'https://picsum.photos/id/26/400/300',
  cover: 'https://picsum.photos/seed/tictactoe-cover/800/600',
  categoryId: 'estrategia',
  category: 'Estratégia',
  difficulty: 'Easy',
  players: '1-2',
  averagePlayTime: '3 min',
  averagePlayTimeMinutes: 3,
  tags: ["Estratégia", "Clássico"],
  featured: true,
  popular: false,
  isNew: false,
  status: 'published',
  version: '1.0.0',
  rating: 4.1,
  gradient: 'from-amber-500 to-orange-600',
  releaseDate: '2024-01-20',
}
