import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'flappy-bird',
  slug: 'flappy-bird',
  title: 'Flappy Bird',
  description: 'Toque para voar e desvie dos canos.',
  shortDescription: 'Voe e desvie dos canos.',
  thumbnail: 'https://picsum.photos/id/217/400/300',
  cover: 'https://picsum.photos/seed/flappy-bird-cover/800/600',
  categoryId: 'reflexo',
  category: 'Reflexo',
  difficulty: 'Hard',
  players: '1',
  averagePlayTime: '5 min',
  averagePlayTimeMinutes: 5,
  tags: ["Arcade", "Casual"],
  featured: false,
  popular: true,
  isNew: false,
  status: 'published',
  version: '1.0.0',
  rating: 4.0,
  gradient: 'from-sky-400 to-blue-500',
  releaseDate: '2024-07-22',
}
