import type { GameConfig } from '@/types/game'

export const config: GameConfig = {
  id: 'tetris',
  slug: 'tetris',
  title: 'Tetris',
  description: 'O lendário jogo de blocos que desafia seus reflexos.',
  shortDescription: 'O lendário jogo de blocos.',
  thumbnail: 'https://picsum.photos/id/36/400/300',
  cover: 'https://picsum.photos/seed/tetris-cover/800/600',
  categoryId: 'reflexo',
  category: 'Reflexo',
  difficulty: 'Hard',
  players: '1',
  averagePlayTime: '20 min',
  averagePlayTimeMinutes: 20,
  tags: ["Clássico", "Puzzle"],
  featured: true,
  popular: true,
  isNew: false,
  status: 'published',
  version: '1.0.0',
  rating: 4.9,
  gradient: 'from-sky-500 to-indigo-600',
  releaseDate: '2024-06-10',
}
